/**
 * Debounced MutationObserver wrapper for LearningSuite's Vue-rendered
 * widgets (accordions, the schedule's list view) that change DOM after the
 * initial page load without a full navigation — see learningsuite-handoff.md
 * §1.1. `debounceMs` collapses a burst of unrelated mutations (e.g. an
 * accordion opening several rows at once) into one re-run.
 *
 * Self-trigger suppression: an adapter's own DOM writes (inserting cards,
 * marking nodes processed) must not re-trigger the observer. An `applying`
 * flag alone does NOT work here — the flag is cleared in `run()`'s finally,
 * but MutationObserver callbacks fire as a microtask *after* the current task
 * completes, so by the time the records generated by our own writes are
 * delivered, `applying` is already false again (confirmed live Sep 2026,
 * tools/audit/32-observe-race.mjs: every adapter write scheduled exactly one
 * redundant extra run, and on the Combined Schedule that extra run was the
 * dayList wipe). Instead, `run()` flushes `observer.takeRecords()` in its
 * finally: records queued *during* the callback are by definition our own
 * writes, and records queued *before* the timer fired were already consumed
 * by an earlier observer callback (microtasks drain before the next task), so
 * the queue is guaranteed empty when `run()` starts — takeRecords can only
 * ever catch self-generated records (pattern verified live,
 * tools/audit/33-observe-fix-check.mjs). The `applying` flag is kept as a
 * cheap synchronous backstop, not the primary mechanism.
 */
export function observeMutations(
  target: Node,
  callback: () => void,
  options: MutationObserverInit = { childList: true, subtree: true },
  debounceMs = 150,
): () => void {
  let timer: ReturnType<typeof setTimeout> | undefined;
  let applying = false;

  const run = () => {
    timer = undefined;
    if (applying) return;
    applying = true;
    try {
      callback();
    } finally {
      applying = false;
      // Discard the records our own writes just queued (see header comment).
      observer.takeRecords();
    }
  };

  const observer = new MutationObserver(() => {
    if (applying) return;
    if (timer !== undefined) clearTimeout(timer);
    timer = setTimeout(run, debounceMs);
  });
  observer.observe(target, options);

  return () => {
    if (timer !== undefined) clearTimeout(timer);
    observer.disconnect();
  };
}
